[package]
name = "rust_lib"
version = "0.1.0"
authors = ["The Appgineer"]
edition = "2021"

[lib]
crate-type = ["cdylib", "staticlib"]

[dependencies]
flutter_rust_bridge = "=2.0.0-dev.26"
log = "0.4"
once_cell = "1.19"
roon-api = { git = "https://github.com/TheAppgineer/rust-roon-api.git", rev = "77cf53c", features = ["browse", "image", "transport"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
simple-logging = "2.0"
tokio = { version = "1.24.1", features = ["macros"] }
