// This file is automatically generated, so please do not edit it.
// Generated by `flutter_rust_bridge`@ 2.0.0-dev.25.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::rust_async::RwLock<BrowseItem>>
@sealed
class BrowseItem extends RustOpaque {
  BrowseItem.dcoDecode(List<dynamic> wire)
      : super.dcoDecode(wire, _kStaticData);

  BrowseItem.sseDecode(int ptr, int externalSizeOnNative)
      : super.sseDecode(ptr, externalSizeOnNative, _kStaticData);

  static final _kStaticData = RustArcStaticData(
    rustArcIncrementStrongCount:
        RustLib.instance.api.rust_arc_increment_strong_count_BrowseItem,
    rustArcDecrementStrongCount:
        RustLib.instance.api.rust_arc_decrement_strong_count_BrowseItem,
    rustArcDecrementStrongCountPtr:
        RustLib.instance.api.rust_arc_decrement_strong_count_BrowseItemPtr,
  );

  String? get imageKey => RustLib.instance.api.browseItemImageKey(
        that: this,
      );

  String? get itemKey => RustLib.instance.api.browseItemItemKey(
        that: this,
      );

  static Future<BrowseItem> newBrowseItem(
          {required RoonApiBrowseItem inner, dynamic hint}) =>
      RustLib.instance.api.browseItemNew(inner: inner, hint: hint);

  String? get subtitle => RustLib.instance.api.browseItemSubtitle(
        that: this,
      );

  String get title => RustLib.instance.api.browseItemTitle(
        that: this,
      );
}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::rust_async::RwLock<roon_api :: browse :: Item>>
@sealed
class RoonApiBrowseItem extends RustOpaque {
  RoonApiBrowseItem.dcoDecode(List<dynamic> wire)
      : super.dcoDecode(wire, _kStaticData);

  RoonApiBrowseItem.sseDecode(int ptr, int externalSizeOnNative)
      : super.sseDecode(ptr, externalSizeOnNative, _kStaticData);

  static final _kStaticData = RustArcStaticData(
    rustArcIncrementStrongCount:
        RustLib.instance.api.rust_arc_increment_strong_count_RoonApiBrowseItem,
    rustArcDecrementStrongCount:
        RustLib.instance.api.rust_arc_decrement_strong_count_RoonApiBrowseItem,
    rustArcDecrementStrongCountPtr: RustLib
        .instance.api.rust_arc_decrement_strong_count_RoonApiBrowseItemPtr,
  );
}
