// This file is automatically generated, so please do not edit it.
// Generated by `flutter_rust_bridge`@ 2.0.0-dev.22.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../backend/roon.dart';
import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

void incCounter({dynamic hint}) => RustLib.instance.api.incCounter(hint: hint);

int getCounter({dynamic hint}) => RustLib.instance.api.getCounter(hint: hint);

Future<void> startRoon(
        {required FutureOr<void> Function(RoonEvent) cb, dynamic hint}) =>
    RustLib.instance.api.startRoon(cb: cb, hint: hint);
