// This file is automatically generated, so please do not edit it.
// Generated by `flutter_rust_bridge`@ 2.0.0-dev.22.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../api/roon_transport_wrapper.dart';
import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

class ZoneSummary {
  final String zoneId;
  final String displayName;
  final ZoneState state;
  final String? nowPlaying;
  final String? imageKey;

  const ZoneSummary({
    required this.zoneId,
    required this.displayName,
    required this.state,
    this.nowPlaying,
    this.imageKey,
  });

  @override
  int get hashCode =>
      zoneId.hashCode ^
      displayName.hashCode ^
      state.hashCode ^
      nowPlaying.hashCode ^
      imageKey.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ZoneSummary &&
          runtimeType == other.runtimeType &&
          zoneId == other.zoneId &&
          displayName == other.displayName &&
          state == other.state &&
          nowPlaying == other.nowPlaying &&
          imageKey == other.imageKey;
}
