// This file is automatically generated, so please do not edit it.
// Generated by `flutter_rust_bridge`@ 2.0.0-dev.22.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'roon.freezed.dart';

@freezed
sealed class RoonEvent with _$RoonEvent {
  const factory RoonEvent.coreFound(
    String field0,
  ) = RoonEvent_CoreFound;
  const factory RoonEvent.coreLost(
    String field0,
  ) = RoonEvent_CoreLost;
}
